project_id: "bilingualcomplaint-system"
location: "us-east1"
staging_bucket: "gs://tfx-artifacts"
pipeline_name: "product_pipeline"
model_output_uri: "gs://tfx-artifacts/pipeline_artifacts/complaints-clf-vertex-training/661860051070/model-deployment-product-pipeline-20241208211710/train-mbert-model_-4941593107952041984/model_output"
model_display_name: "tf-mbert-model-product"
endpoint_display_name: "tf-mbert-endpoint-product"
deployed_model_display_name: "tf-mbert-deployed-product"
