name: Run Deployment Pipeline

on:
  push:
    branches:
      - Dev
    paths:
      - "deployment/**"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: bilingualcomplaint-system

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deployment/deployment_requirements.txt

      - name: Run Deployment for Department
        run: python deployment/deployment_pipeline.py deployment/department.yml

      - name: Run Deployment for Product
        run: python deployment/deployment_pipeline.py deployment/product.yml
