name: Run Final Pipeline Script

on:
  push:
    branches:
      - Dev  # Trigger workflow on push to the 'Dev' branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: bilingualcomplaint-system

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/pipeline_requirements.txt

      # Step 5: Run the final pipeline script
      - name: Run Final Pipeline Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}  # Google Cloud credentials
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}        # Slack Webhook URL
        run: |
          python pipeline/final_pipeline.py
