name: Continuous Integration

on:
  push:
    paths:
      - 'data-preprocessing-pipeline/dags/scripts/preprocessing.py'
      - 'tests/**'
  pull_request:
    paths:
      - 'data-preprocessing-pipeline/dags/scripts/preprocessing.py'
      - 'tests/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/data_preprocessing_pipeline/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r data_preprocessing_pipeline/requirements.txt
        pip install pytest

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      env:
        PYTHONPATH: ${{ runner.workspace }}/Automated-BiLingual-Complaint-System
      run: |
        pytest tests/ --log-file=tests/pytest.log

    - name: Upload pytest logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-logs-failure
        path: tests/pytest.log

    - name: Upload pytest logs on success
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-logs-success
        path: tests/pytest.log