name: Run Training Pipeline

on:
  push:
    branches:
      - Dev
    paths:
      - "train/**"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: bilingualcomplaint-system

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r train/requirements.txt

      - name: Run Training for Department
        run: python train/submit_train_pipeline.py --config train/train-department.yml

      - name: Run Training for Product
        run: python train/submit_train_pipeline.py --config train/train-product.yml
